### ISSUE TITLE
Step 1: Save Money

### ISSUE THREAD

**Issue by nelsonic** [edwardcodes/Around-the-World#1]
The most important "skill" in travelling ☀️ 🌴
is spending the _least_ amount of cash per day. 📉 
Therefore, your _mission_ for the next _week_ is: to _spend_ as little cash as possible. 💸 🚫 😉 

# Todo:

+ [ ] Get an "extract" from the ATM ("multibanco") and take a photograph of it.  🏧 
+ [ ] Count the money you have in your wallet and any other "available cash" you have. 💰 
  + [ ] Don't leave _any_ money "lying around", make sure it's _all_ tracked. 🔢 
+ [ ] Make a note in your notebook (_or phone_) whenever you spend money on _anything_. 📝 
+ [ ] At the end of the week, share how much cash you spent (_just the total_). ❓

**Comment by carolrmc** [comment]
👍🏻

**Comment by nelsonic** [comment]
[![image](https://user-images.githubusercontent.com/194400/45885242-d24c2e80-bdad-11e8-9192-9962d5b69a8c.png)](https://youtu.be/AlCqyZEXM1I)
https://youtu.be/AlCqyZEXM1I

**Comment by nelsonic** [comment]
Saving as _much_ money as possible ***before*** your adventure should be the step that comes ***before*** even _thinking_ about where to go. Even if it's less "_exciting_" it's absolutely _essential_. 

This _really_ good guide: https://thesavvybackpacker.com/backpacking-through-europe-planning/
includes quite a lot of tips/advice on budgeting.
