### ISSUE TITLE
Pre-Travel Checklist

### ISSUE THREAD

**Issue by nelsonic** [edwardcodes/Around-the-World#15]
***`before`*** you even _think_ of going anywhere, you need a _comprehensive_ checklist of "***all the things***" you want/need to be taking with you to avoid any nasty/expensive surprises.

If you need "inspiration" for what to add to this list, see: https://www.onebag.com/checklist.html
or _search_ for "travel checklist": https://duckduckgo.com/?q=travel+checklist

# "Gear" Packing List 📸 

All the things you _don't_ want to forget (_or lose_) that will make your trip even more **`epic`**!

+ [ ] **iPhone** (_obvs_... I wonder if people travel without smartphones just to "challenge" themselves?_)
+ [ ] **Passport** (_store this in an **accessible** but **secure** pocket of your rucksack 
with a small amount of cash e.g: €50 in smaller notes e.g: 10's_)
  + [ ] Take a Photo of your Passport or ID card (_or both_) "details" page and send it to me+Inês.
+ [ ] **_Concealed_** (_under shirt_) **money/document belt** "pouch" kept on your person at all times. 
  e.g: https://www.lifeventure.com/en-pt/products/accessories/rfid-travel-belt-pouch
  + [ ] Keep the bare minimum in the belt pouch to avoid "bulking" it too much (_keep it invisible!_) 
  + [ ] Figure out how to keep the Travel Pouch safe when you shower! (e.g: take a "Zip Lock" bag in the 
+ [ ] **Discrete In-ear** "bud" **Earphones**, essential for music _discrete_ turn-by-turn maps directions. (_there will be times where you want to appear like you are "just listening to music" but not disclose what/which phone you have ... in Lisbon it's "normal" to have an iPhone. but there are countries/cities where it's a clear sign of [perceived] "wealth" and makes you a "**target**" for **mugging/theft** especially if **travelling alone**!_)
+ [ ] **Camera** - as we've discussed capturing the journey is almost as important as _going_ on the trip! #9 
  + [ ] **GorillaPod** (_flexible_) Tripod (Magnetic) https://joby.com
  + [ ] Window **Suction Mount** https://joby.com/us-en/suction-cup-and-locking-arm-jb01330-bww
  + [ ] **_Spare_ MicroSD Card** in "holder" case. (_the bigger the SD card the better! e.g 128GB!_)
  + [ ] "**Selfie Stick**"! There will be _plenty_ of situations to use one to capture more in photos/videos!
  Doubles as a self-defence weapon in the hands of someone who knows how to defend themself. 
+ [ ] **Laptop** (_optional_) see: #8 

# Clothes 👕 

Clothes are the _least_ expensive part of your "pack" and can _easily_ be bought on-location.
If you "forget" or "lose" an item of clothing, it's not a "big deal", just use the MasterCard to buy whatever you need. 

+ [ ] **10 Pairs** of: (_this way you only need to do laundry twice on your trip!_)
  + [ ] Underwear 
  + [ ] Socks
+ **10 T-Shirts** 👕 
  + [ ] At _least_ 2 @dwyl T-Shirts. (_this is where you add immediate value to the "family biz" [**`home`**](https://github.com/dwyl/home) 
by taking **video** in cool/interesting/historic places #3  featuring the @dwyl logo we can make an **awesome** "**welcome home** montage"!_)
  + [ ] Expect/Plan to buy at _least_ one "**Souvenir T-Shirt**" but _resist_ the temptation to get one you'll _never_ wear again. If you find one that has a great design or is meaningful to your trip - and cannot be ordered "online" cheaper when you get back - get it! that's the whole point of having a bigger bag #4 !
+ [ ] Spare "Smart Casual" Shoes (_if you don't have shoes that look new-ish, let me know today!_)
+ [ ] 1 x **Hoodie**
+ [ ] 1 x **Warm/Waterproof Coat** ☔️ 
+ [ ] **Spare Jeans**/Trousers 👖(_the darker the better_!)
+ [ ] 1 x "**_Smart_ Shirt**" for going out to dinner with your new friends!! 
+ [ ] 1 x "**_Smart_ Jersey**" again, for going out to "nice" places (_I have one for you!_)
+ [ ] _Lightweight_ **Flip-Flops** (_for showering and/or beach_)
+ [ ] **Swimsuit**. Even if you don't **plan** to "swim". You need this in the Nordics!! #12 
  The lighter the better. doubles as "spare shorts". wear these on "laundry day" so you can wash both pairs of jeans and all your underwear! 😉 
+ [ ] **_Warm_ Pijamas**  (_usually the "bottom half" is enough as you can always use a T-Shirt on top_), sleeping in Hostels / shared rooms this is **essential**. You might be **tempted** to sleep in your boxers, trust me, you will be _cold_! And you don't want to be wondering in a corridor at night to use the W/C in your underwear ... 
+ [ ] **Hat** 🎩  - this is good for both blocking out the sun (_yes, it's still sunny in Spain/Italy/Greece!_) and for "identity protection" preferably a black/dark _nondescript_ baseball cap. _Avoid_ wearing this in in *international* train stations if you don't want the security to "flag" you. But it's good to wear *on* the train, especially when you want to _avoid_ eye-contact with "weirdos". Take it off when you want to "connect" with someone. 
+ [ ] ***Sunglasses***. 😎  https://youtu.be/xFbJoXJBIIA?t=120 (_if you don't have, buy at Carca market!_)
+ [ ] **Gloves**. The Nordics are _cold_ especially at night! ❄️ 🌃 

> **Note** on Doing **Laundry**: ***don't wait*** until you have "used up" _all_ your clothes, by then it's **too late**! You need to **plan** this. When you get down to 2 pairs of socks/underwear, ask the hostel manager/reception about laundry and reserve a "slot". 

## _Expect_ the _Best_. _Plan_ for the _Worst_! (_So that you can Avoid it!_)

+ [ ] **Cash** in **Shoe**(s). Keep a single (_bigger denomination_) note under the insole of your shoe. Yes, this doubles the "value" of your shoes if they are _stolen_ but if you you are _mugged_ it might be the only thing you get to _keep_! 
+ [ ] "**Spare Phone**" e.g: the Moto G5 which you can use in places where you _really_ don't want to look like you have money. 
+ [ ] ***Combination Lock*** + Cable #6 

# Travel Apps! 📱 

_Don't_ leave "home" without these!!

+ [ ] Download ***Duolingo*** to learn _useful_ phrases and _pronounciation_ 
+ [ ]  Download Google Translate
  + [ ] Download any Languages for the countries you will be visiting. (_no need to get them **all** `before` you leave as you will have Wifi in All Hostels and many trains!_) I recommend getting: 
    + [ ] Spanish
    + [ ] French
    + [ ] German!
+ [ ] Download **Trip Advisor** App. it has the _best_ advice for what to see/do in most cities. 
  + [ ] Download the "City Pack" for the _first_ couple of cities on your plan https://github.com/edwardcodes/Around-the-World/issues/2#issuecomment-426232492
+ [ ] Download the ***HostelWorld*** App, it's the best for managing bookings.
+ [ ] **Booking.com** App is a good _second_ option but HostelWorld is 
+ [ ] Download **Google Maps** App (_the best for turn-by-turn walking directions for finding places!_)
  + [ ] Download "**Offline Map**" for wherever you are to your phone whenever you have Wifi
+ [ ] **Rail Planner** https://www.eurail.com/en/plan-your-trip/rail-planner-app
+ [ ] Download **Monzo** App (_if you are able to from the PT App Store..._) 

Further reading: 
+ https://www.hostelworld.com/blog/best-travel-apps
+ https://www.hostelculture.com/blog/article/21-best-damn-travel-apps-for-backpacking
